version: '3'

services:
  cleaningschedule:
    container_name: cleaning-schedule
    build:
      context: .
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/cleaningSchedule
      - SPRING_DATASOURCE_USERNAME=cleaning_schedule_app
      - SPRING_DATASOURCE_PASSWORD=example
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8082:8082
    expose:
      - 8082

  db:
    image: postgres:13.1-alpine
    container_name: db
    restart: always
    environment:
        - POSTGRES_USER=cleaning_schedule_app
        - POSTGRES_PASSWORD=example
        - POSTGRES_DB=cleaningSchedule
    ports:
      - 5432:5432
    expose:
      - 5432

  frontend:
    build:
      context: ./CleaningSchedule
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    container_name: frontend